name: cmabo-linux
channels:
  - gpytorch
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - gxx_linux-64
  - gcc_linux-64
  - swig
  - pip:
      - torch==1.13.1
      - torchvision==0.14.1
      - torchaudio==0.13.1
      - gpytorch==1.8.1
      - botorch==0.6.6
      - gpy
      - cma
      - gym
      - gym[box2d]
      - gym[mujoco]
      - pandas==1.4.0

